### ISSUE TITLE
Chore: use `application/json` as content type in all public API methods

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#1175]
# Feature Request

In order to have consistency across all public APIs, every controller method must `@Produce` and `@Consume` `application/json`. This means that all plaintext responses, for example the response to a contract-negotiation-initiation would have to be wrapped in a JSON object.

We could even go so far as to devise a global `ApiResult` object, that wraps _every_ response object. API methods would still return the proper HTTP status code (200 and others), and carry the `ApiResult` in the response body. 

We have to check how the OpenApi generator plugin behaves in this situation, it would be bad to lose information about the returned JSON object. Maybe we can counter this with custom annotations somehow.

## Which Areas Would Be Affected?
Data Management API

## Why Is the Feature Desired?
Having a consistent API scheme is desirable and will make code-generated clients easier to handle.

## Solution Proposal
The `ApiResult` and could look like the this:
```java
public class ApiResult<T> {
   private T content; //only non-null if no error
   private Integer errorCode; //null if no error, maybe leave out?
   private String errorMessage; //null if no error
}
```

the `errorCode` could contain either the HTTP status code, which seems redundant, or it could contain application error codes, should we ever support those, or we could leave it out altogether. (I'm in favor of leaving it out)

## Type of Issue
Improvement

## Tasks
- [ ] Investigate how OpenApi behaves with those generic objects
- [ ] Update all `@Produces` and `@Consumes` annotations, move to the class level
- [ ] wrap every controller response in an `ApiResult`

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
`errorCode` and `errorMessage` should be left in the HTTP response and not reported in the body, because the response body should be protocol agnostic.
For now I would keep `content` as the only field.

**Comment by paullatzelsperger** [comment]
> `errorCode` and `errorMessage` should be left in the HTTP response and not reported in the body, because the response body should be protocol agnostic. For now I would keep `content` as the only field.

at that point we could also just wrap whatever is now returning a `String` in some object, that would save that wrapping layer.
