### ISSUE TITLE
Milestone 1 Release Criteria

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#310]
@paullatzelsperger and I created this issue to compile the criteria for our Milestone 1 release, which we are doing in partnership with Catena-X.

We have broken down the deliverable into two top-level categories: EDC Functionality; and the Catena-X Milestone Deliverable. All items are currently set to __mandatory__.

# 1. EDC Functionality Deliverable

## Contract Offer
- [x]  IDS Multipart handlers need to be cleaned up and merged (Denis, PR #285 ) __Due Monday__
- [x] Verify contract offer request flow (message dispatchers and handlers) (Denis, Dominik, #306) __Due Tuesday__
- [x] Verify that asset Index supports IN criterion (Jim and Paul, #307) __Due Monday__
- [x] Verify Policy subsystem integration (Jim #308) __Due Tuesday__

## Contract Negotiation
- [x] In progress (Julia and Ronja, #284 ) __Due Wednesday__
- [x] Implement Cosmos ContractNegotiationStore (Paul #309) __Due Thursday__

## Data Transfer
- [x] Data transfer needs to use TPM instead of TPS (Brendan and Paul, #301) __Due Tuesday__

## Control API
- [x] Implement a security filter (Denis #302) __Due Monday__
- [x] Implement a control endpoint to return contract offers to a client (Denis, #303) __Due Monday__
- [x] Implement a control endpoint to handle contract negotiation (Ronja and Julia, #304) __Due Wednesday__

## Artifact Release Pipeline 
(Paul, Andrea #305)
__Due Wednesday__
- [x] Version EDC starting at 0.0.1 
- [ ] Every successful build on main creates a snapshot (Not mandatory, workaround is to publish to Maven local)

## Samples and Documentation 
(Andrea)
__Due Thursday__
- [x] Verify all samples and documentation 

# 2. Catena-X Milestone Deliverable
(Andrea and Paul)

The Milestone Deliverable consists of a __Repository__, __Sample Data__, and an __Azure Deployment__. The repository will be a dedicated one for Catena-X outside of the EDC organization. This will demonstrate how to consume EDC published binaries. This should be done by one of the participants. Andrea, can you?

## Build System
- [x] Create a simple Gradle multi-module build.

## Launchers
 __Due Wednesday__
- [x] Consumer/provider launchers (based on sample 5)
- [x] Properties configuration (for local execution)
- [x] Docker file for Azure deployment
- [x] Publish Docker images to a Docker repo

## Data Loaders 
__Due Wednesday__
- [x] Sample assets, contract definitions (policies) are generated.

## Deployment 
__Due Thursday__
- [x] Terraform files for populating Vault
- [ ] Data Loaders are executed through Terraform (?)
- [ ] DAPS is deployed and configured through Terraform
- [x] Terraform is used to deploy any other required resources

## Documentation 
__Due Thursday__
- [x] How to build the repository and set up a local and Azure-based deployment environment
