### ISSUE TITLE
Investigate java-potentially-weak-cryptographic-algorithm CodeQL alerts

### ISSUE THREAD

**Issue by Izzzu** [eclipse-dataspaceconnector/DataSpaceConnector#789]
## Description
As a part of an issue #648  5 alerts related to **Use of a potentially broken or risky cryptographic algorithm** were dismissed. This issue aims to investigate if the alerts can stay dismissed or they require some actions or fixes.

More information about the CodeQL alert: https://codeql.github.com/codeql-query-help/java/java-potentially-weak-cryptographic-algorithm/

Places in the code where the alerts were raised:

[extensions/iam/decentralized-identity/identity-did-crypto/src/main/java/org/eclipse/dataspaceconnector/iam/did/crypto/key/KeyPairFactory.java:43](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/3b07d9c7fe49ebe50b082082858479e5a6465c85/extensions/iam/decentralized-identity/identity-did-crypto/src/main/java/org/eclipse/dataspaceconnector/iam/did/crypto/key/KeyPairFactory.java#L43)
![image](https://user-images.githubusercontent.com/4217554/156333834-ffca1fe9-92bb-427e-8e3e-165ea23c7546.png)

[extensions/iam/decentralized-identity/identity-did-crypto/src/main/java/org/eclipse/dataspaceconnector/iam/did/crypto/key/KeyPairFactory.java:65](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/3b07d9c7fe49ebe50b082082858479e5a6465c85/extensions/iam/decentralized-identity/identity-did-crypto/src/main/java/org/eclipse/dataspaceconnector/iam/did/crypto/key/KeyPairFactory.java#L65)
![image](https://user-images.githubusercontent.com/4217554/156333894-79f50d8b-f7aa-425d-af8d-eb246048772d.png)

[extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/JsonCommitObject.java:81](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/5b165bd39f0187337893d66736c08f870f2de2db/extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/JsonCommitObject.java#L81)
![image](https://user-images.githubusercontent.com/4217554/156333923-54deb61f-5d63-48d5-b9e3-0b15e9bbbc0d.png)

[extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/jwt/Fingerprint.java:55
](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/5b165bd39f0187337893d66736c08f870f2de2db/extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/jwt/Fingerprint.java#L55)![image](https://user-images.githubusercontent.com/4217554/156333954-14b05f9d-5816-43ac-a9a7-53d8f784837a.png)

Please note that the code could have changed after the scan was performed and some alerts might not be applicable anymore.

## Tasks
- [ ] Investigate if the alerts need to be fixed in the code or should stay dismissed
- [ ] Fix the alerts if applicable
- [ ] Document the reasoning behind dismissing the alerts (code comments or [CodeQL doc](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/docs/developer/decision-records/2022-02-11-codeql/README.md)) if applicable

**Comment by jimmarino** [comment]
Hi, @Izzzu The Fingerprint.java use of SHA-1 is required for interop with AAD. If needed, ping me offline and we can follow up with one of our contacts on the identity team to see if there is an alternative.
